### PR TITLE
Postgres

### PR DESCRIPTION
**Pull request by wujunhua**
setup local db with aws postgres db?

### CODE REVIEW

**Comment by Raymond-Zhu** [comment]
Almost. What you have there isn't setting up localdb with postgres on AWS. You're working directly with the Postgres DB. If you want to have a local db for development and use postgres for production you can take a look at this. 

https://www.coderedcorp.com/blog/django-settings-for-multiple-environments/

**Comment by wujunhua** [comment]
Yea, i was going to do that, but how do we connect local db to aws? something like this? 

`if 'RDS_HOSTNAME' in os.environ:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': os.environ['RDS_DB_NAME'],
            'USER': os.environ['RDS_USERNAME'],
            'PASSWORD': os.environ['RDS_PASSWORD'],
            'HOST': os.environ['RDS_HOSTNAME'],
            'PORT': os.environ['RDS_PORT'],
        }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'localdb',
            'USER': 'localdb',
            'PASSWORD': 'localdb',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }'

or does aws ec2 set this up?

**Comment by Raymond-Zhu** [comment]
I'm not sure what you mean by connect local db to aws? If you mean transfer the data over from local to production db?

**Comment by wujunhua** [comment]
Yea that what i mean.. haha

**Comment by Raymond-Zhu** [comment]
Uhhh you can probably export the local db data into CSV file. Then connect to postgres on AWS and import it.

**Comment by wujunhua** [comment]
Just pushed a new commit, this should work, updated the read me as well.

**Comment by Raymond-Zhu** [comment]
What we could do is set environment variables separately. Something like 
DATABASES = {
     'default': { 
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ['DB_NAME'],
        'USER': os.environ['DB_USERNAME'],
        'PASSWORD': os.environ['DB_PASSWORD'],
        'HOST': os.environ['DB_HOSTNAME'],
        'PORT': os.environ['DB_PORT'],
}

If you want to work with local, just set the environment variables to the local db and if you want to work with the AWS one set the variables to the AWS's DB info.

**Comment by wujunhua** [comment]
Yea,

`if 'RDS_HOSTNAME' in os.environ:
DATABASES = {
'default': {
'ENGINE': 'django.db.backends.postgresql_psycopg2',
'NAME': os.environ['RDS_DB_NAME'],
'USER': os.environ['RDS_USERNAME'],
'PASSWORD': os.environ['RDS_PASSWORD'],
'HOST': os.environ['RDS_HOSTNAME'],
'PORT': os.environ['RDS_PORT'],
}
else:
DATABASES = {
'default': {
'ENGINE': 'django.db.backends.postgresql_psycopg2',
'NAME': 'localdb',
'USER': 'localdb',
'PASSWORD': 'localdb',
'HOST': 'localhost',
'PORT': '5432',
}
}`

If we are working in local db, it will work locally, and similarly for aws. 

I asked a friend and he said, this template is created by setting up RDS in aws ec2? 

Either way, we can work on local db. Since we also have to create models like the one u created in aws.

**Pull request merged**
